# Generated by Django 5.2.4 on 2025-07-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_avatars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='user_avatars/'),
        ),
    ]
